services:
  - type: web
    name: suite-cre-langgraph-agent
    runtime: python
    plan: starter  # or free tier
    buildCommand: pip install uv && uv sync
    startCommand: uv run langgraph start --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false  # Add manually in dashboard
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /health