services:
  - type: web
    name: langgraph-tools-agent
    runtime: python
    plan: starter  # or free tier
    buildCommand: pip install uv && uv sync
    startCommand: langgraph dev --config ./langgraph.json --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false  # Add manually in dashboard
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGSMITH_TRACING
        sync: false
      - key: LANGSMITH_ENDPOINT
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        sync: false
    healthCheckPath: /health